# Site settings
title: Izzan's Blog
email: 
description: "hoyo huyu"
baseurl: ""
url: "http://aahmadizzan.github.io"
twitter_username: regrezan
github_username:  ahmadizzan

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
